const digital = [
    {
        name:"game_night",
        description:"",
    },
    {
        name:"spring_celeb",
        description:"",
    },
    {
        name:"synchro_ending",
        description:"",
    },
    {
        name:"exhibition",
        description:"",
    },
    {
        name:"leaf_gradient",
        description:"",
    },
    {
        name:"chess",
        description:"",
    },
    {
        name:"fall",
        description:"",
    },
    {
        name:"stupid_ml",
        description:"",
    },
    {
        name:"reflection_2leg",
        description:"",
    },
    {
        name:"line_leaves",
        description:"",
    },
    {
        name:"miguel_rio_branco",
        description:"",
    },
    {
        name:"synchro_you",
        description:"",
    },
    {
        name:"Alessar",
        description:"",
    },
    {
        name:"reflection_jump",
        description:"",
    },
    {
        name:"sunny",
        description:"",
    },
    {
        name:"setup",
        description:"",
    },
    {
        name:"fight",
        description:"",
    },
    {
        name:"touch_me_baby",
        description:"",
    },
    {
        name:"snowy_noho",
        description:"",
    },
    {
        name:"synchro_html",
        description:"",
    },
    {
        name:"la_food_zine",
        description:"",
    },
    {
        name:"hotballoon",
        description:"",
    },
    {
        name:"spring_poster",
        description:"",
    },
    {
        name:"latern_poster",
        description:"",
    },
    {
        name:"chiny",
        description:"",
    },
    {
        name:"dark_cloud",
        description:"",
    },
    {
        name:"style_transfer",
        description:"",
    },
    {
        name:"flipBrasil",
        description:"",
    },
    {
        name:"hw2_creative_design",
        description:"",
    },
    {
        name:"mismorize",
        description:"",
    },
    {
        name:"rotation",
        description:"",
    },
    {
        name:"dice",
        description:"",
    },
    {
        name:"heart",
        description:"",
    },
    {
        name:"svg_bg_p2",
        description:"",
    },
    {
        name:"svg_prototype",
        description:"",
    },
    {
        name:"svg_bg_p6b",
        description:"",
    },
    {
        name:"svg_bg_p6e",
        description:"",
    },
    
];

export default digital;