const artworks = [
    {
        name:"self_writing_zoom",
        description:"",
    },
    {
        name:"line_art",
        description:"",
    },
    {
        name:"seat",
        description:"",
    },
    {
        name:"self_writing",
        description:"",
    },
    {
        name:"fans",
        description:"",
    },
    {
        name:"seals",
        description:"",
    },
    {
        name:"dragon_drawing",
        description:"",
    },
    {
        name:"fei_cheng",
        description:"",
    },
    {
        name:"line_art_zoom",
        description:"",
    },
    {
        name:"fans_draw",
        description:"",
    },
    {
        name:"yuhan_map",
        description:"",
    },
    {
        name:"sutra",
        description:"",
    },
    {
        name:"faces",
        description:"",
    },
    {
        name:"wave",
        description:"",
    },
    {
        name:"drill",
        description:"",
    },
    {
        name:"masked_portrait",
        description:"",
    },
    {
        name:"my_collection",
        description:"",
    },
    {
        name:"campus_map",
        description:"",
    },
    {
        name:"collage",
        description:"",
    },
    {
        name:"xin_jing",
        description:"",
    },
    {
        name:"haunfield",
        description:"",
    },
    {
        name:"tulip",
        description:"",
    },
    {
        name:"monkey_figurine",
        description:"",
    },
    {
        name:"self_portrait",
        description:"",
    },
    {
        name:"boymother1",
        description:"",
    },
    {
        name:"boymother2",
        description:"",
    },
    {
        name:"xingshu",
        description:"",
    },
    {
        name:"black_space",
        description:"",
    },
    {
        name:"scene",
        description:"",
    },
    {
        name:"leaf_falling",
        description:"",
    },
    {
        name:"one_hundred",
        description:"",
    },
    {
        name:"nurseshavehair",
        description:"",
    },
    {
        name:"monster_figurine",
        description:"",
    },
];

export default artworks;